// Paste in a shared file or at the top of [src/app/page.tsx](cci:7://file:///home/sym/code/CascadeProjects/windsurf-project/lowdine/src/app/page.tsx:0:0-0:0)
export const tonyIntroQuotes: string[] = [
  "Hey, friend — you look hungry and indecisive. You've come to the right joint.",
  "Welcome to The Lowdine. Don't worry, we keep things quiet here.",
  "You found us. Or maybe we found you. Either way, pull up a stool.",
  "Psst… you didn't hear about this place from me, capisce?",
  "Keep your voice down — we don't want the whole city showing up.",
  "What's the matter, can't decide on dinner? Happens to the best of us.",
  "You look like someone who could use a nudge in the right direction.",
  "The Lowdine's off the record, pal. You didn't see nothin'.",
  "Ah, another lost soul in the land of takeout menus.",
  "Relax. You're among friends here — hungry, confused friends.",
  "Careful out there. Too many options'll make a person dizzy.",
  "Word is, you're lookin' for a place to eat. I might know a few.",
  "The Lowdine's no place for drama — just decisions.",
  "Sit tight. Tony'll take care of ya.",
  "No passwords, no secret knocks — just a wheel and a whisper.",
  "You're early. Good. The less people know about this spot, the better.",
  "You didn't see a neon sign, right? Perfect. That's how we like it.",
  "You look like someone who argues with the menu. Let's fix that.",
  "Welcome back — or maybe you never left. Time moves funny down here.",
  "Hungry? Conflicted? You got that 'I'll eat anything' look.",
  "This joint's for people who've had one too many dinner debates.",
  "Ah, a fresh face! You didn't hear about us from social media, did ya?",
  "Keep it down, keep it classy, and maybe we'll find you a table.",
  "If anyone asks, we're just a book club, got it?",
  "You look like a decision waiting to happen.",
  "The Lowdine's open late — and we don't judge your cravings.",
  "Good taste, lousy timing — story of my life. Let's spin the wheel.",
  "Welcome to the underground of appetite, friend.",
  "Shh… listen close. That sound? That's dinner destiny calling.",
  "I ain't promising miracles — just a good meal and a quiet conscience.",
];

export const tonySpinQuotes: string[] = [
  "Hold your horses, I'm thinkin'...",
  "Easy, kid, the wheel's got opinions of its own.",
  "You can't rush greatness—or lunch.",
  "Let's see what the universe—or Yelp—has to say.",
  "Spin's in motion. Keep those expectations low and your appetite high.",
  "You ever notice how indecision smells like takeout?",
  "Alright, I'm consultin' the dinner spirits... they're loud tonight.",
  "Don't tap too fast, I ain't a slot machine.",
  "Good things take time, bad meals happen quick.",
  "Gimme a second, I'm runnin' the numbers on your cravings.",
  "Patience, pal. The wheel's feelin' moody tonight.",
  "This thing spins faster than my cousin Vinnie's alibi.",
  "I'm divinin' your destiny—don't break the concentration.",
  "Quiet down, this is delicate culinary magic.",
  "If this lands on soup again, I swear it's rigged.",
  "C'mon, baby, give us somethin' classy.",
  "You ever feel like dinner decides *you*?",
  "Don't look at me, I just work here.",
  "The wheel's thinkin'. Let it cook—pun intended.",
  "I hope you like surprises, 'cause I don't control this thing.",
  "Maybe tonight's the night we find somethin' worth rememberin'.",
  "Spin's almost done—don't breathe too hard, it gets nervous.",
  "You got good taste, but let's see if fate agrees.",
  "You sure you wanna know? Once I tell ya, there's no goin' back.",
  "It's hummin'—that's a good sign. Or a bad one. Hard to tell.",
  "Wheel's talkin'. I just translate.",
  "This thing's got more drama than a holiday dinner.",
  "Don't rush art, friend. Especially edible art.",
  "Almost there... I can smell the marinara already.",
  "C'mon, c'mon, give me somethin' with real napkins."
];

export const tonyResultQuotes: string[] = [
  "Alright, here's what I got for ya. Don't say I never did nothin' nice.",
  "Bingo. That's a solid joint right there.",
  "Would ya look at that? Even the wheel's got taste.",
  "This one's a sleeper hit. Tell 'em Tony sent ya.",
  "Here's your spot. Keep it on the Lowdine, yeah?",
  "Not bad, huh? Try not to gloat when it's good.",
  "I knew the wheel liked you. It's got class today.",
  "Okay, pal, here's where your fate's pointin'.",
  "That's dinner sorted. You're welcome.",
  "Boom. Mystery solved. Appetite saved.",
  "Ah, a respectable choice—no embarrassment here.",
  "Hey, look at that. Even I didn't see that one comin'.",
  "Mark my words, this place'll hit the spot.",
  "Now that's a meal worth leavin' the couch for.",
  "The wheel speaks, and it says: eat classy tonight.",
  "This joint's legit. Just don't go tellin' everyone.",
  "There it is. A dinner that won't start a family argument.",
  "I'd eat there myself if I wasn't glued to this counter.",
  "Looks like destiny's got good taste tonight.",
  "You're in luck—this place does the sauce right.",
  "If this ain't your style, blame the wheel, not me.",
  "I got a good feelin' about this one, friend.",
  "Here ya go: the kind of joint that remembers your name.",
  "You could do worse. You often do.",
  "That one? Oh yeah, you're eatin' good tonight.",
  "The Lowdine delivers again. I never doubted it.",
  "Write this one down before you forget it.",
  "That's the pick. Don't overthink it. Just go.",
  "Congratulations, the wheel says you're eatin' fancy.",
  "There it is—your dinner destiny, hot and fresh."
];

// Rotating lines to show at the bottom while Tony is thinking (after the initial line)
export const tonyThinkingQuotes: string[] = [
  "Tony is thinking...",
  "Consulting the wheel... keep your hat on.",
  "Running the neighborhood by memory...",
  "Checking if Nonna would approve...",
  "Cross-referencing with good napkins only...",
  "Eliminating places with sticky tables...",
  "Asking the kitchen gods for a sign...",
  "Putting the word out—quietly...",
  "Alright, give me a second, I'm thinkin' here.",
  "These things take time, kid — even genius needs a minute.",
  "Hold tight, I'm runnin' the numbers on your appetite.",
  "I'm consultin' the dinner spirits. They're opinionated tonight.",
  "Hmm... pasta? Pizza? Existential dread? Tough call.",
  "Don't rush me, I'm makin' art over here.",
  "You can't hurry hunger, pal. It's a delicate science.",
  "The wheel's whisperin'. I'm listenin'.",
  "Patience — brilliance brews slow, like a good sauce.",
  "I'm triangulatin' your taste buds. This could take a sec.",
  "Don't worry, I got connections in high kitchens.",
  "I'm calculatin' the flavor trajectory. It's complicated math.",
  "Quiet down — I'm hearin' somethin'… could be tacos.",
  "I'm thinkin'... but the wheel's got an attitude today.",
  "C'mon, brain, don't fail me now. We got a hungry customer.",
  "I once solved a dinner dispute in under ten seconds. This ain't that night.",
  "My gut says Italian, but my gut says that every time.",
  "The universe is alignin'... or maybe that's just indigestion.",
  "Hang tight — I'm readin' the omens in leftover marinara.",
  "Could take a minute. The culinary cosmos moves slow.",
  "Let's see… somethin' cheap, somethin' cheerful, somethin' edible.",
  "You ever stare into the fridge and hope for divine guidance? Same.",
  "Almost there — I can feel it simmerin'.",
  "The wheel's spinnin', but I'm spinnin' harder.",
  "I'm talkin' to my sources — mostly otherworldly chefs.",
  "This could go either way, friend. Hold onto your napkin.",
  "One wrong turn and we end up at Olive Garden. Gimme a second.",
  "You're lucky I'm a professional. Amateurs panic at times like these.",
  "I'm channelin' the power of generations of indecisive eaters.",
  "Don't rush perfection — or me. Same difference."
];